name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma aire_stationnement et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/aire_stationnement/schema_aire_stationnement.json
        # frictionless validate --schema schema/aire_stationnement/schema_aire_stationnement.json schema/aire_stationnement/exemple_aire_stationnement.csv
    - name: Vérification du schéma a et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/arret_tc/schema_arret_tc.json
        # "frictionless validate --schema schema/arret_tc/schema_arret_tc.json schema/arret_tc/exemple_arret_tc.csv
    - name: Vérification du schéma cheminement et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/cheminement/schema_cheminement.json
        # frictionless validate --schema schema/cheminement/schema_cheminement.json schema/cheminement/exemple_cheminement.csv
    - name: Vérification du schéma mobilier et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/mobilier/schema_mobilier.json
        # frictionless validate --schema schema/mobilier/schema_mobilier.json schema/mobilier/exemple_mobilier.csv
    - name: Vérification du schéma obstacle et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/obstacle/schema_obstacle.json
        # frictionless validate --schema schema/obstacle/schema_obstacle.json schema/obstacle/exemple_obstacle.csv
    - name: Vérification du schéma service et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/service/schema_service.json
        # frictionless validate --schema schema/service/schema_service.json schema/service/exemple_service.csv
    - name: Vérification du schéma signaletique et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/signaletique/schema_signaletique.json
        # frictionless validate --schema schema/signaletique/schema_signaletique.json schema/signaletique/exemple_signaletique.csv
    - name: Vérification du schéma troncon et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema schema/troncon/schema_troncon.json
        # frictionless validate --schema schema/troncon/schema_troncon.json schema/troncon/exemple_troncon.csv
    - name: Vérification du datapackage
      run: |
        # frictionless validate datapackage.json
